site_name: ALLAPPS offset Fix for HOS 14.0.0
extra_css:
  - stylesheets/extra.css
extra_javascript: [js/color_blocks.js]
plugins: []
theme:
  name: material
  palette:
    scheme: slate
    primary: grey
    accent: red
  features:
    - header.autohide
    - content.tabs.link
markdown_extensions:
    - admonition
    - toc: # https://python-markdown.github.io/extensions/toc/
          permalink: True
          toc_depth: 4
    - md_in_html
    - attr_list
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.highlight
    - pymdownx.critic
    - pymdownx.superfences
    - pymdownx.keys
    - pymdownx.details
    - pymdownx.tasklist
nav:
   - Intro: 'index.md'
   - Prerequisites: 'pre.md'
   - LayoutEditor: 'layout.md'
   - LayoutKit: 'laykit.md'
   - Switch Theme Injector: 'swthmeinj.md'
   - Thanks & Credits: 'thanks.md'